#!/bin/sh

# Set these paths appropriately

BIN=/Users/Barth/Documents/Tweets_collection/TreeTagger/bin
CMD=/Users/Barth/Documents/Tweets_collection/TreeTagger/cmd
LIB=/Users/Barth/Documents/Tweets_collection/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
