#!/bin/sh

# Set these paths appropriately

BIN=/Users/Barth/Documents/Tweets_collection/TreeTagger/bin
CMD=/Users/Barth/Documents/Tweets_collection/TreeTagger/cmd
LIB=/Users/Barth/Documents/Tweets_collection/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan-utf8.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
